version: '3.8'

services:
  # Blue Service - Primary by default
  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - PORT=${PORT:-3000}
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:${PORT:-3000}"  # Expose for direct chaos triggers
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT:-3000}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 10s
    networks:
      - app_network
    restart: unless-stopped

  # Green Service - Backup by default
  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - PORT=${PORT:-3000}
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:${PORT:-3000}"  # Expose for direct chaos triggers
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT:-3000}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 10s
    networks:
      - app_network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"  # Public endpoint
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
      - nginx_logs:/var/log/nginx  # Shared log volume
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PORT=${PORT:-3000}
    depends_on:
      - app_blue
      - app_green
    networks:
      - app_network
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

  # Alert Watcher Service - Monitors logs and sends Slack alerts
  alert_watcher:
    image: python:3.11-slim
    container_name: alert_watcher
    volumes:
      - ./watcher.py:/app/watcher.py:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - nginx_logs:/var/log/nginx:ro  # Read-only access to Nginx logs
      - watcher_state:/app/state  # Persistent state for maintenance mode
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD:-2}
      - WINDOW_SIZE=${WINDOW_SIZE:-200}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC:-300}
      - MAINTENANCE_MODE=${MAINTENANCE_MODE:-false}
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && python -u watcher.py"
    depends_on:
      - nginx
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  nginx_logs:  # Shared volume for Nginx access logs
  watcher_state:  # Persistent storage for watcher state